### ISSUE TITLE
Tasks

### ISSUE THREAD

**Issue by blt950** [Vatsim-Scandinavia/controlcenter#375]
Could CC have some kind of internal workflows?

**Workflow 1 - ATSimTest**
A request for ATSimTest workflow has been requested. A place where a mentor could create a request for token, TD get notified and can reply back it's completed. In addition to this it could be logged if the student has passed the ATST or not, and use it to control check solo endorsements and exams.

**Workflow 2 - Controller Feedback**
When we receive controller feedback, an assigned person can approve to forward it to controller.

The more useful workflows we can add in here, the more useful this feature will be, as we can build it to serve multiple purposes rather than one.

**Comment by thor** [comment]
I'm revisiting this as it's a high priority, and I have a few follow-up questions, @blt950.

1. Are there other use cases with workflows that have been requested that we're not aware of? 

2. Have there been use cases that require complicated workflows requiring advanced process designs?

The current scope is simple enough that sticking to models with some state machine implementation is sufficient. It's possible to blow it out of the water, and perhaps there are other workflows we want to execute where this makes sense. For example, there are packages such as Workflower, which has BPMN support if you *really* want to get *heavy* with the workflows, but it's a bit much. They solve much more complex workflows than I think we have.

If we want something *in the middle*, then I'm curious to use something like [Laravel Workflow](https://laravel-workflow.com/docs/introduction). It provides abstractions for workflows, activities and the asynchronous nature of workflows running in the background for more extended periods. The truth is, though, that some of its background job functionality is more interesting than the workflows and activities directly. 🤔 I believe that's because those parts would be much larger and more time-consuming to implement with friendly interfaces and user journeys than the actual transitions between activities.[^hm]

[^hm]: This can be reduced to a single status column if you trade elegancy for simplicity.

Depending on 1. and 2., what did you have in mind for re-use? I can primarily think of the state machine itself, which a third-party composer package could provide if we'd like. Were there particular features as part of a workflow engine you have considered using in different places? 👀 

---

Alternatively, let's find out which one we want the most, split it into its separate features and tasks, and implement it with a design that considers that we want to re-use any shareable workflow or activity-related code rather than duplicate it. 👌

**Comment by blt950** [comment]
Workflower is overkill, but I also share the interest for Laravel Workflow - though also the part that it's the background job functionality is the more interesting one than the other stuff.

I wonder if native Laravel models and some good data columns would do the trick for us and the two quite simple workflows we have. The flows in general will be quite simple and be like:

1. Request of something is made
2. Someone receives the request
3. Someone receives a notification that they've a request to do something
4. Someone completes/denies the request with a comment
5. The request is fulfilled (and somoene else is maybe notified of this)

What's maybe the more tricky part is how to make it a bit modular without inserting workflow code into other parts of the code creating a mess. So perhaps we need some simple scaffolding, and then a folder like `app/workflows/atsimtest.php` that has some predefined functions that get called in some stages?

Parts that I think we maybe want, but quickly add complexity:
- Feedback workflow would make sense to be sent to all <insert FIR> staff, instead of one specific user perhaps. 
- Should there be a log of what has happened to the flow, or is it just "do this" and then it's history and maybe a record of if it has been done or not.
- Probably something else?

To answer your question @thor 
1. No, this is mainly thought for ATST, but then feedback came in mind after months of thinking. So currently the amount of workflows will probably be very low. 
2. No and will doubtly happen in the future as is

While writing this I thought of a way to specify this task further. The workflows in this context are basically "Approval flows" that are send to one or multiple users. This user(s) accept/deny the thing, which then does something in our application or just manually outside our context by the user. This would be the simplest way to describe this functionality, if we keep it within this box it shouldn't require too much witchcraft brewery to get working. In terms of scaleability, based on my comment that we squeezed the lemon just to get two flows, I don't think this will be an issue for the forseable future (famous last words).

**Comment by blt950** [comment]
Workflow/Tasks is the new feature we've talking about to at least streamline a bit the manual work that exists today. How it's thought to work is that a user requests something, it shows up in your tasks-list. Then when you complete it, it'll trigger some automation in the background or just a notification back that something is done.

**The tasks I can think of pre-EUD Core (as today):**
- Mentor/TA requests ATST Token. TD approves when done. Requester receives notification. Approval is logged in training activity.
- (Standard type S1) Mentor/TA requests ATST Upgrade. TD approves when done. Requester recieves notification. Upgade logged in training activity.
- (Standard type S2+) Training request is completed and automatically requests upgrade. TD approves when upgraded. TA receives notification. Upgrade logged in training activity.
- User submits ATC feedback. ? get notified. When approved, the controller in question gets forwarded the feedback.

**Tasks I can think of post-EUD CORE (when released)**
- Mentor/TA requests ATST Token. TD approves when done. Requester receives notification. Approval is logged in training activity.
- (Standard type S1) Mentor/TA requests ATST Upgrade. TD approves and request is sent via API. Requester recieves notification. Upgade logged in training activity.
- (Standard type S2+) Training request is completed and automatically requests upgrade. TD approves and request is sent via API including the examination PDF as attachment. TA receives notification. Upgrade logged in training activity.
- User submits ATC feedback. ? get notified. When approved, the controller in question gets forwarded the feedback.
