### ISSUE TITLE
Upgrade to Laravel 10

### ISSUE THREAD

**Issue by blt950** [Vatsim-Scandinavia/controlcenter#546]
There is no breaking changes between 9 and 10, so should be an alright update to do.

**Comment by thor** [comment]
I've been tempted to do this because it should be minimal with work, but the bigger question is how to handle versioning for this upgrade. If we're very semantic in our versioning, this should _strictly speaking_ be Control Center v5. It shouldn't be, but we must be aware of that and address it clearly in our release notes.

I can feel my human tendency to put too much meaning in a version come into play when I think of the upgrade. If anything, that's perhaps a greater motivator to resist the urge to skip around semantic versioning rules.

Luckily, it's a "small" breaking change. "Hey, we're dropping support for PHP version blah. This only impacts you if you're running `control-center` directly in a PHP installation and your PHP version is blah or older."

**Comment by blt950** [comment]
Laravel 9.x supports PHP 8.0 - 8.2
Laravel 10.x supports PHP 8.1 - 8.2

Other than that, no breaking changes. As Laravel's new versioning model is that they will deprecate functions a lot slower and push more larger (non-semantic imo) versions onwards. Hence Laravel LTS no longer is a thing.

In Control Center eyes this is a minor upgrade and doesn't entitle a major version v5 tag. This is because Docker is our recommended and supported ways of usage. A warning should be sufficient for those few or none that perhaps doesn't use Docker for some reason.

That being said, I'd really want your hands on other more feature tasks than dependency updates @thor , reach out to me on PM when you have time to be assigned higher priority tasks <3

**Comment by thor** [comment]
> Laravel 9.x supports PHP 8.0 - 8.2 Laravel 10.x supports PHP 8.1 - 8.2
> 
> Other than that, no breaking changes. As Laravel's new versioning model is that they will deprecate functions a lot slower and push more larger (non-semantic imo) versions onwards. Hence Laravel LTS no longer is a thing.
> 
> In Control Center eyes this is a minor upgrade and doesn't entitle a major version v5 tag. This is because Docker is our recommended and supported ways of usage. A warning should be sufficient for those few or none that perhaps doesn't use Docker for some reason.

Gotcha; if a bare-metal deployment of control-center isn't attached to the versioning anymore then that makes it a lot easier and allows us to chuck it straight out. I'll chuck it out of the milestone and 💥.

> That being said, I'd really want your hands on other more feature tasks than dependency updates @thor , reach out to me on PM when you have time to be assigned higher priority tasks <3

<3

**Comment by blt950** [comment]
I mean, it's a bit up to discussion. I look at CC bare-metal docker setup as our versioning baseline. If a user decides to install CC in the unsupported and unrecommended way, meaning manually it's on their own risk. What we can do is to at least provide warnings if we do minor updates where an main dependency can cause an issue.

Then the question is what causes an major version in CC? I think we stick to the same definition as always, but exclude dependency updates that are already covered in our Docker setup (such as PHP is automagically included with correct versions and everything).

What do you think @thor ?

**Comment by blt950** [comment]
Note for update: `shell_exec` needs to be enabled for migrations to work in production after upgrading to Laravel 10. Experience from Handover.
