### ISSUE TITLE
API endpoints to get list of ATC

### ISSUE THREAD

**Issue by bedrich-schindler** [Vatsim-Scandinavia/controlcenter#594]
Currently, there are just endpoints to retrieve list of:

* MAE endorsements
* Examiners endorsements
* Visiting ATC endorsements
* Solo endorsements (Training / S1) [TBH we do not know difference between S1 and Solo]

We need endpoint (or multiple endpoints) to list all our ATC. We need:

* First name, last name (or both), CID, VATSIM ATC Rating
* Whether is active/inactive ATC
* Highest approved rating in ATC portal (it can differ for example if ATC transfers between VACC or when ATC does not complete refresh for its ATC license but for lower one)

Whether we implement this as /atc/active, /atc/inactive or in one endpoint, we need to somehow filter the list. If you list visiting ATC in endorsements endpoint, I am not sure whether we want them in list of ATC, because in such case we would have to filter them on client. Second problem is that I am not sure whether we can distinguish between inactive ATC and random user who logged in into CC. Maybe we need to filter them using subdivision code?

Use case for that is to display ATC rooster on our web.

Do you think we can implement such endpoint, it is the most critical part for us as we are now unable to display ATC rooster.

**Comment by blt950** [comment]
Hey there @bedrich-schindler, before I go to the details of this suggestion I'd like to take you through some thoughts. I'm answering for this and #595 as well in this message.

First, VATSCA's philosophy is that we will never display full names on our websites. The reason for that is because then people's full names are indexed by search engines and they get possible to Google for instance. Hence for our endorsement tables we show first name and CID which is plenty to identify the person for someone within the community, and also providing a button to login to CC for more details (including last names). Example: https://vatsim-scandinavia.org/atc/visiting-controller/

Now to your suggestion, if you still wish to do it as described above that's technically possible. We can of course give out a lot of details in the API, it's the implementing service of the API that decides what should be visible, so technically it shouldn't matter. My question here is what you mean by highest approved rating? CC just reads one rating really, which is the VATSIM-rating that is fed through VATSIM Cert in the nightly updates.

_Note: The difference between Solo and S1 is that S1 is a special endorsement that is often used differently than a VATEUD Solo Endorsement. In VATSCA we use that for temporary S1 "solos" while in training and then issue them permanent S1 endorsement when they've completed our S1 programme. If you don't use S1 in your VACC, then  you can simply ignore it._

**Comment by blt950** [comment]
@bedrich-schindler Is this still wished functionality, as we haven't heard anything back for 3 weeks? :)

**Comment by bedrich-schindler** [comment]
Let's solve issue with names in #595. I would expect to return VATSIM ID only OR VATSIM ID + full name. I can imagine to display VATSIM ID only to public and full name for logged users, but solve it in #595.

Maybe we can skip "Highest approved rating" at all. We just need to know list of our active ATC and inactive ATC + solo, visitings, examiners (which are all already implemented).I haven't check the code, but the only problem can be detection of active and inactive ATC. Everybody can log in into the CC that makes list of members messy. We already observed situation when there was newly registered ATC with S1 assigned at our subdivision, he was originally assigned to UK (I think) and transferred to our subdivision on his own - not official transfer. Or what about visiting ATC - such ATC can be active, can have for example C1 rating, but only S3 rating approved  at some FIR/vACC so he/she should not be part of active list, but only at list of visiting controllers. It might not be the problem, I just speak about than so we know edge cases.

But it is high priority for us as every division must have their list available on their website (at least part of newly prepared policy)

**Comment by blt950** [comment]
There's a lot of requests here now. Based on how I read this, I suggest the following:
- Close #595 
- This task is about making an `api/users` call, which include:
  - ID
  - Full name
  - Rating
  - ATC Active boolean
  - The user's role
  - The user's endorsements: visiting, examiner, solo, s1, masc etc.

Then you can supply parameters of what kind of data you want. E.g. send in `withEndorsements=true` to get the endorsement data etc. That way you can still request minimal data for a faster response.

I think this will be a nice way to clean up the API that today is a bit all over the place and replying in different formats on every request. Making it user-centric and provide the requested data of the users, a bit super simple GraphQL if you may. This API call can then deprecate the old ones in the long run.

What do you think @bedrich-schindler?

>But it is high priority for us as every division must have their list available on their website (at least part of newly prepared policy)

I believe you're talking about GCAP. Note that GCAP doesn't force you to have an public name exposing roster, just having one in general. The member list in #510 covers this requirement, and is behind login so you can also safely expose names etc. The same goes for solo endorsements, they can also be behind login - I've validated that with two SUPs.

**Comment by blt950** [comment]
I've created a branch for the API suggestion above. This will provide all requested data and also centralise the endpoint and data structure. Currently out for review #621 until it gets merged.

**Comment by blt950** [comment]
Merged now and will be released shortly.
